baseURL = "https://romanromero.es"
languageCode = "es-es"
title = "Román Menor | Procuradora"
theme = "infinity-hugo"
removePathAccents = true


# HTML before the closing </head>
[params]
customHead = ""

# Navigation
[params.navigation]
logo = ""
home = "Inicio"
about = "Partidos Judiciales"
service = "Servicios"

# Hero Area
[params.hero]
enable = true
bg = "images/header-bg.jpg"
title = "MARÍA DEL CARMEN ROMÁN MENOR"
subtitle = "Procuradora | 630129578 | carmen@romanmenor.es"
btnText = "Saber más"

# counter
disableCountdown = true
countdownYear = "2022"
countdownMonth = "12"
countdownDay = "31"

# About Section
[params.about]
enable = true
heading = "Partidos Judiciales"
description = "Los ámbitos de actuación son Ciudad Real, Alcázar de San Juan, Almagro, Almadén, Daimiel, Manzanares, Puertollano, Tomelloso, Valdepeñas, Villanueva de los Infantes y en Toledo capital."

[[params.about.sliderItem]]
image = "images/about/1.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[[params.about.sliderItem]]
image = "images/about/3.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"


# Service Section
[params.service]
enable = true
title = "Servicios"
subtitle = ""
[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-strategy"
title = "Asesoramiento"
description = "Especialista en Derecho Procesal"
delay = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-circle-compass"
title = "Notificationes al día"
description = "Todas las resoluciones judiciales serán notificadas en el mismo día"
delay = "0.2s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-anchor2"
title = "Control de Plazos"
description = "Recordatorios de señalamientos, plazos y requerimientos"
delay = "0.4s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-globe"
title = "Impulso Procesal"
description = "Acelerar la tramitación de los procedimientos"
delay = "0.6s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-strategy"
title = "Rápido y Eficaz"
description = "Redacción de escritos de trámite y presentación el mismo día"
delay = "0.8s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-circle-compass"
title = "Versatilidad"
description = "Tramitaciones ante cualquier organismo público y privado"
delay = "1s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-anchor2"
title = "Diligenciado"
description = "Despachos, exhortos, edictos, oficios y mandamientos"
delay = "1.2s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-globe"
title = "Subastas, Embargos y Alzamientos"
description = "Con asistencia en cerrajería y otros servicios relacionados"
delay = "1.5s"

# Call to Action Section
[params.cta]
enable = false
bg = "images/call-to-action.jpg"
title = "Subscribe to our mailing list"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"

[params.contact]
enable = false
title = "Contacto"
subtitle = "Si quiere contactar para más información sobre su caso específico y presupuestos, por favor rellene el formuario a continuación y me pondré en contacto con usted lo antes posible."
